// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKgssmVPJFVXcUpDMXTmVigIX3kvr7Ryc',
    appId: '1:942831628763:web:4c5a262385a9eb5702b7fe',
    messagingSenderId: '942831628763',
    projectId: 'fir-bbb36',
    authDomain: 'fir-bbb36.firebaseapp.com',
    storageBucket: 'fir-bbb36.firebasestorage.app',
    measurementId: 'G-HM16ZM8CV5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAld5mASoY07qH6FDbVi1U4yXC_EboZ7S8',
    appId: '1:942831628763:android:15ec012a88a131cc02b7fe',
    messagingSenderId: '942831628763',
    projectId: 'fir-bbb36',
    storageBucket: 'fir-bbb36.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCDx6mC4Qt8qe7HH4X576ZLeCnz7eiYNE',
    appId: '1:942831628763:ios:8a97f72966bd475402b7fe',
    messagingSenderId: '942831628763',
    projectId: 'fir-bbb36',
    storageBucket: 'fir-bbb36.firebasestorage.app',
    androidClientId: '942831628763-i6tnm1vthck66jppc2qe6u4jstcnuhkl.apps.googleusercontent.com',
    iosClientId: '942831628763-eb089jbqp4k47ukhiseboru8vgdbh473.apps.googleusercontent.com',
    iosBundleId: 'com.example.splashGoogleLogin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCCDx6mC4Qt8qe7HH4X576ZLeCnz7eiYNE',
    appId: '1:942831628763:ios:8a97f72966bd475402b7fe',
    messagingSenderId: '942831628763',
    projectId: 'fir-bbb36',
    storageBucket: 'fir-bbb36.firebasestorage.app',
    androidClientId: '942831628763-i6tnm1vthck66jppc2qe6u4jstcnuhkl.apps.googleusercontent.com',
    iosClientId: '942831628763-eb089jbqp4k47ukhiseboru8vgdbh473.apps.googleusercontent.com',
    iosBundleId: 'com.example.splashGoogleLogin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAKgssmVPJFVXcUpDMXTmVigIX3kvr7Ryc',
    appId: '1:942831628763:web:98623f6fbc6578da02b7fe',
    messagingSenderId: '942831628763',
    projectId: 'fir-bbb36',
    authDomain: 'fir-bbb36.firebaseapp.com',
    storageBucket: 'fir-bbb36.firebasestorage.app',
    measurementId: 'G-TVT1E8C9WM',
  );

}